[versions]
agp = "8.13.2"
kotlin = "2.0.21"

coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

lifecycleRuntimeKtx = "2.10.0"
lifecycleViewModelKtx = "2.10.0"
lifecycleViewModelCompose = "2.10.0"
activityCompose = "1.12.4"
kotlinxCoroutinesPlayServices = "1.8.1"
composeBom = "2024.09.00"

compose-compiler = "1.5.15"
pdfbox = "2.0.27.0"
poi = "5.2.3"

mlkitLanguage = "17.0.4"
mlkitTranslate = "17.0.1"

multidex = "2.0.1"

# ==============================
# Libraries
# ==============================

[libraries]

# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewModelKtx" }

# Activity
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# Compose UI
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

# PDF
pdfbox-android = { module = "com.tom-roush:pdfbox-android", version.ref = "pdfbox" }

coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }

# ML Kit
mlkit-language-id = { module = "com.google.mlkit:language-id", version.ref = "mlkitLanguage" }
mlkit-translate = { module = "com.google.mlkit:translate", version.ref = "mlkitTranslate" }

# Multidex (POI 대비)
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

androidx-lifecycle-viewmodel-compose = {group = "androidx.lifecycle",name = "lifecycle-viewmodel-compose",version.ref = "lifecycleViewModelCompose" }


# ==============================
# Test
# ==============================

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# ==============================
# Plugins
# ==============================

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
